### ISSUE TITLE
cfLoadExtension does not work with custom extensions

### ISSUE THREAD

**Issue by nischayn22** [WikiWorks/Canasta#10]
On using cfLoadExtension('MyCustomExtension'); extensions from ./extensions directory aren't loaded and wfLoadExtension is required to be called.

**Comment by jeffw16** [comment]
This is intended behavior.

**Comment by nischayn22** [comment]
But the Readme says otherwise.

**Comment by jeffw16** [comment]
Got it, I adjusted the README, thank you
