### ISSUE TITLE
 error: composer.json: patch does not apply

### ISSUE THREAD

**Issue by datawiki** [WikiWorks/Canasta#20]
Cloned as instructed and ran docker-compose up -d --build

 => ERROR [source  8/29] RUN set -x;  cd /var/www/mediawiki/w  && git apply /tmp/core-fix-composer-for-GoogleAnal  3.5s
------
 > [source  8/29] RUN set -x;   cd /var/www/mediawiki/w         && git apply /tmp/core-fix-composer-for-GoogleAnalyticsMetrics.diff:
#16 3.475 + cd /var/www/mediawiki/w
#16 3.475 + git apply /tmp/core-fix-composer-for-GoogleAnalyticsMetrics.diff
#16 3.477 error: patch failed: composer.json:77
#16 3.477 error: composer.json: patch does not apply
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c set -x;   cd $MW_HOME     && git apply /tmp/core-fix-composer-for-GoogleAnalyticsMetrics.diff]: exit code: 1

**Comment by jeffw16** [comment]
Disclaimer: This comment doesn't address the problem, but I'll make it for the sake of addressing your issue more immediately.

Could you please try to go to the `docker-compose.yml` file and replace:

```
    build:
      dockerfile: Dockerfile
      context: .
```

with:

```
    image: ghcr.io/wikiworks/canasta:latest
```

and then run `docker-compose up -d` **without** the `--build` flag.

**Comment by jeffw16** [comment]
@vedmaka, do we still need this patch? https://github.com/WikiWorks/Canasta/blob/master/_sources/patches/core-fix-composer-for-GoogleAnalyticsMetrics.diff

**Comment by datawiki** [comment]
Worked. Thank you very much.
