### ISSUE TITLE
Extension UserFunctions 1.35 results Error 500

### ISSUE THREAD

**Issue by datawiki** [WikiWorks/Canasta#26]
Tried everything. Fresh install, git clone, copy and paste, etc. but enabling UserFunctions 1.35 results in an error 500. There without the system runs fine.

The old UserFunctions 1.27 & require_once "$IP/extensions/UserFunctions/UserFunctions.php"; does work however.

**Comment by yaronkoren** [comment]
What about the UserFunctions version included in Canasta (1.35), but with the require_once call? It looks like the issue might be that wfLoadExtension() support was not added to UserFunctions until after 1.35.

**Comment by yaronkoren** [comment]
Okay, I just upgraded the version of UserFunctions being used - I believe this fixes the error. Feel free to re-open if not.
