### ISSUE TITLE
Cannot Conncect to Database Host during setup

### ISSUE THREAD

**Issue by irwando** [WikiWorks/Canasta#29]
I'm attempting to run this on my Synology Diskstation.  I'm getting the following error during MediaWiki Setup:

> Cannot access the database: :real_connect(): (HY000/1130): Host '172.24.0.4' is not allowed to connect to this MySQL server.
> Check the host, username and password and try again. If using "localhost" as the database host, try using "127.0.0.1" instead (or vice versa).

Notes from my install:

- The "_initdb" directory doesn't exist after doing a git clone, and docker-compose up throws an error since it can't bind.  I manually created it. 
- I changed the MW_SITE_SERVER env variable to "Diskstation.local"
- I changed the PORT env vairable to "8083"
- I created a simple bridge network and attached all the containers to it
- I verified that from the web container I can ping "db" and get a response

Is there any additional configuration needed?  I believe typically mySQL does disallow remote connections by default and they need to be enabled. Is that needed here?

**Comment by jeffw16** [comment]
What did you place in the `_initdb` directory before the first run? Did you add things to it after the first run?

**Comment by irwando** [comment]
I didn't put anything into it, I just created the directory. If I didn't then the container wouldn't start.

Here's my end-end process:

`Irwin@DiskStation:/volume1/docker/docker-compose$ git clone https://github.com/WikiWorks/Canasta.git ./canasta/
Cloning into './canasta'...
remote: Enumerating objects: 371, done.
remote: Counting objects: 100% (371/371), done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 371 (delta 204), reused 189 (delta 80), pack-reused 0
Receiving objects: 100% (371/371), 133.57 KiB | 432.00 KiB/s, done.
Resolving deltas: 100% (204/204), done.
Irwin@DiskStation:/volume1/docker/docker-compose$ cd  canasta/
Irwin@DiskStation:/volume1/docker/docker-compose/canasta$ ls
total 116
drwxrwxrwx+ 12 Irwin users  4096 Feb  1 18:44 .
drwxrwxrwx+ 16 Irwin users  4096 Feb  1 18:44 ..
drwxrwxrwx+  2 Irwin users  4096 Feb  1 18:44 backups
drwxrwxrwx+  2 Irwin users  4096 Feb  1 18:44 backup_scripts
drwxrwxrwx+  2 Irwin users  4096 Feb  1 18:44 config
-rwxrwxrwx+  1 Irwin users  1671 Feb  1 18:44 docker-compose.yml
-rwxrwxrwx+  1 Irwin users 36437 Feb  1 18:44 Dockerfile
-rwxrwxrwx+  1 Irwin users   158 Feb  1 18:44 .env.example
drwxrwxrwx+  2 Irwin users  4096 Feb  1 18:44 extensions
drwxrwxrwx+  8 Irwin users  4096 Feb  1 18:44 .git
drwxrwxrwx+  3 Irwin users  4096 Feb  1 18:44 .github
-rwxrwxrwx+  1 Irwin users   160 Feb  1 18:44 .gitignore
-rwxrwxrwx+  1 Irwin users   127 Feb  1 18:44 hadolint.yaml
drwxrwxrwx+  2 Irwin users  4096 Feb  1 18:44 images
drwxrwxrwx+  2 Irwin users  4096 Feb  1 18:44 kubernetes
-rwxrwxrwx+  1 Irwin users 11748 Feb  1 18:44 README.md
drwxrwxrwx+  2 Irwin users  4096 Feb  1 18:44 skins
drwxrwxrwx+  7 Irwin users  4096 Feb  1 18:44 _sources
Irwin@DiskStation:/volume1/docker/docker-compose/canasta$ mkdir _initdb
Irwin@DiskStation:/volume1/docker/docker-compose/canasta$ cp .env.example .env
Irwin@DiskStation:/volume1/docker/docker-compose/canasta$ vi .env
Irwin@DiskStation:/volume1/docker/docker-compose/canasta$ docker-compose pull
Pulling db            ... done
Pulling elasticsearch ... done
Pulling web           ... done
Irwin@DiskStation:/volume1/docker/docker-compose/canasta$ docker-compose up -d
Creating network "canasta_default" with the default driver
Recreating canasta_db_1            ... done
Recreating canasta_elasticsearch_1 ... done
Recreating canasta_web_1           ... done
Irwin@DiskStation:/volume1/docker/docker-compose/canasta$`

and the .env file:

`PORT=8083
MYSQL_PASSWORD=mediawiki
PHP_UPLOAD_MAX_FILESIZE=10M
PHP_POST_MAX_SIZE=10M
PHP_MAX_INPUT_VARS=1000
MW_SITEMAP_SUBDIR=
MW_SITEMAP_IDENTIFIER=mediawiki
MW_SITE_SERVER=Diskstation.local`

**Comment by jeffw16** [comment]
Thanks for that info. Did you change the Docker Compose file?

**Comment by irwando** [comment]
Nope, I left that alone. Only touched the .env file and created an empty _initdb 

I am running this on a Synology Diskstation if that makes a difference.  I am running about 12 other Docker containers successfully, but perhaps there is something specific to that environment?

**Comment by jeffw16** [comment]
It sounds like there was a custom bridge network constructed for this, done via the CLI perhaps, since there were no modifications made to the Docker Compose manifest. Canasta can't guaranteed to run successfully if that is the case.

If there are 12 other containers already running, it may be that they are interfering with the operation of Canasta somehow.

**Comment by irwando** [comment]
For this instance there was no other network.  The exact docker-compose is:

version: '3.1'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --expire_logs_days=3 --secure-file-priv=""
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE, fix error mbind: Operation not permitted
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-mediawiki}
      - MYSQL_DATABASE=mediawiki
    volumes:
      - ./_initdb:/docker-entrypoint-initdb.d
      - mysql-data-volume:/var/lib/mysql

  web:
    image: ghcr.io/wikiworks/canasta:latest
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - db
      - elasticsearch
    links:
      - db
    environment:
      # Sourced from .env
      - MW_SITE_SERVER=${MW_SITE_SERVER:-http://localhost}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_POST_MAX_SIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-1000}
      - MW_SITEMAP_SUBDIR
      - MW_SITEMAP_IDENTIFIER
    volumes:
      - ./extensions:/var/www/mediawiki/w/extensions
      - ./skins:/var/www/mediawiki/w/skins
      - ./config:/mediawiki/config
      - ./images:/mediawiki/images
      - sitemap:/mediawiki/sitemap

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  mysql-data-volume:
  elasticsearch:
  sitemap:

**Comment by jeffw16** [comment]
Hmm, one thought I had: are you running as root or prepending each command with `sudo`? Such as, when you start the Canasta stack, do you use:

```
sudo docker-compose up -d
```

Because `_initdb/` is a bind mount and should be owned by `root`.

**Comment by amalpaul54111** [comment]
Actually, I encountered a similar issue with Canasta in my local environment, and that was just due to a _low disk space_. Finding more space in my disk fixed the issue. Try to make sure that the disk where docker saves the images and containers have enough space. Even though I have a separate partition for my home directory, docker default to save the containers in `/var/lib/docker`
