### ISSUE TITLE
Double download of Chameleon skin

### ISSUE THREAD

**Issue by yaronkoren** [WikiWorks/Canasta#30]
It looks like the Chameleon skin is being downloaded twice - once via Git in Dockerfile, and once via Composer in composer.local.json. Is that true? If so, should one of those be removed?

**Comment by jeffw16** [comment]
@vedmaka do you have an idea on this one?

**Comment by vedmaka** [comment]
@jeffw16 good catch! yep, it looks like the one being downloaded from Gerrir is surplus

**Comment by yaronkoren** [comment]
Fixed now, I think.
